DROP TABLE orders;
DROP TABLE uses CASCADE CONSTRAINTS;
DROP TABLE writes;
DROP TABLE links_to;
DROP TABLE produces;
DROP TABLE subscribes_to;
DROP TABLE has;
DROP TABLE fanclub_membership;
DROP TABLE payment_method CASCADE CONSTRAINTS;
DROP TABLE studio;
DROP TABLE movie CASCADE CONSTRAINTS;
DROP TABLE rental;
DROP TABLE purchase;
DROP TABLE movie_review;
DROP TABLE user_acc CASCADE CONSTRAINTS;


